### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by Jblew** [andywiecko/MyLinuxConfig#1]
https://github.com/andywiecko/MyLinuxConfig/blob/ccc6842be7d149de5e1c2a37b351536a0f9d9b1f/Makefile#L63

Just wanted to say that this is a great idea for sharing config among project developers. I'll try to convince my teammates to use the same approach!

Thanks, and keep going :) +you can close it

**Comment by andywiecko** [comment]
Thanks for the comment :)

Best
Andrzej
